# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b1b4c7373b298c535c815d98521843ae15f6402af4a3c555f5af9cba6e92430acbc0de9ea0e9d16921077278dc5f1b02a658e9a2a208fe5350e2621369d16cb

test:
  secret_key_base: 10a3fe0e668c2e9aa7aff3e861d59fc897bb824559011436b13854ee8ac8eeda25e7f1d9d6fa4bdf6bf60f1b6d5f6936d2cf81817c4692c6ff1582c2889d6ce9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
